[package]
name = "zanim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "zanim-cli"
path = "src/zanim-cli.rs"

[dependencies]
structopt = "0.3.15"